### ISSUE TITLE
Keyboar Paired but nothing diplayed

### ISSUE THREAD

**Issue by mciucci65** [Hamberthm/esp32-bt2ps2#6]
Hi Hamberthm,

After you replyed to me on YouTube as you suggested I checked the GNDs and they are in common. The esp32 is powered via the USB port. Keyboard paired correctly.

I tried to enter the debug mode as you wrote by defining the _ESP32_PS2DEV_DEBUG_ variable but afterwards I got compilation errors.

#define _ESP32_PS2DEV_DEBUG_ 0x1
![Screenshot 2023-12-12 181545](https://github.com/Hamberthm/esp32-bt2ps2/assets/101509798/ff5ced04-0bb7-45fc-ac46-7bdb4c691d11)

**Comment by Hamberthm** [comment]
Hi there! Sorry for the delay. December was not a good year ending for me, I lost a family member and then went on with construction at home, and then vacations.

Enabling debug is not as straight forward as defining the keyword. The code lacks the functions to spit out the dbg messages, it was made on the Arduino environment and I later ported it to VS Code,  you'll have to adapt them to work on your current platform.

Here you have a working DBG build, it spits out messages using the printf function. BEWARE this is an older build, and lacks MANY of the last bug fixes. You can use it to see what you have to do to get DBG working on the latest build: [https://1drv.ms/u/s!AlKre4_rNmpJiMF-5ZoirLGUKMYQ7g?e=tN2MW4](url)

**Comment by Hamberthm** [comment]
Hi there, someone has posted in my first video ([link](https://www.youtube.com/watch?v=2PVjWfAAJFE)) that he has it working for an Agon Light2 like yours. Check for SteveLovejoy's comment.

Maybe you can ask him how he got it working. If you found something important should be added to the README regarding setup on an Agon Light2, you can tell me and I'll be pleased to add it.

So I consider this issue closed!

**Comment by mciucci65** [comment]
Thank you for your answer. I'm so sorry to hear about your recent loss.
Yes I think he is using your software because I had already solved and inserted it by mentioning you and inserting the link to your GitHub in the keyboards compatible with the SBC Agon.

The problem I had was very simple: the ESP module was broken.

Thank you so much for your support. It would be interesting to make a variant to switch from PS/2 to USB perhaps via a switch.

**Comment by mciucci65** [comment]
https://docs.google.com/spreadsheets/d/1-6_sz6l-vJW5rFg3M0Y6bwC0hmFS7U6PPNjIZ9plrM8/edit?fbclid=IwAR0nHLyEWDt9u6kfQ8sm9wdA0zNlBNsbkKcfCymPKWE6WWvjtqveapsmQHg#gid=0

**Comment by Hamberthm** [comment]
Glad, very glad to hear it works! 😃
I also had a broken ESP32, it drove me mad until I realized. Maybe I broke it by using external and port power at the same time, I really don't know.

**Comment by mciucci65** [comment]
thank you again for your support and your project.

**Comment by Hamberthm** [comment]
PD: You have a typo on the URL on that file, it has a point at the end and the webpage won't load

**Comment by mciucci65** [comment]
at the end of google calc  you can find my post as Jarod with your github mention and link.

**Comment by Hamberthm** [comment]
Yeah, I was referring to the link in the spreadsheet to this github, I think I just fixed it, but it removed the hyperlink, don't worry about it!
