### ISSUE TITLE
Typing a 6 outputs a period

### ISSUE THREAD

**Issue by jfed6000** [Hamberthm/esp32-bt2ps2#9]
Just built this, and it is awesome.  The only issue I have had is that typing a '6' outputs a period.  Haven't had a chance to try to track this down yet.  The computer with ps/2 is running a custom OS.  Could be there (although wired keyboard outputs 6 fine).

Thanks for making this.

**Comment by jfed6000** [comment]
Nevermind.  Must have been a temporary glitch.  All working now!

**Comment by Hamberthm** [comment]
Thanks for the positive feedback, glad it worked!
